algoTeam3/Problem_Solving

BOJ/14938.서강그라운드/oh_14938.java

oh_13938.java

---

BOJ/14938.서강그라운드/chan_14938.java
BOJ/1520. 내리막길/chan_1520.java
BOJ/1753.최단경로/chan_1753.java
BOJ/2665.미로만들기/chan_2665.java

BOJ 1520 내리막길, BOJ 2665 미로만들기, BOJ 14938 서강그라운드, BOJ 1753 최단경로

---

SWEA/1263.사람 네트워크2/oh_1263.java

SWEA1263.사람 네트워크2 oh_1263.java

---

BOJ/11403. 경로찾기/oh_11403.java

BOJ 11403. 경로찾기 oh_11403.java

---

BOJ/16064. Coolest Ski Route/oh_16064_floyd.java

거 자꾸 시간 초과 떠서 일단 플로이드로 풀었습니다 선처해주십셔

 BOJ  16064. Coolest Ski Route

---

BOJ/11657.타임머신/oh_11657.java

BOJ  11657.타임머신

---

BOJ/1865. 웜홀/oh_1865_bellman.java

BOJ 1865. 웜홀

---

BOJ/11657.타임머신/ch_11657.java
BOJ/16064. Coolest Ski Route/ch_16064_floyd.java
BOJ/1738. 골목길/ch_1738.java
BOJ/1865. 웜홀/ch_1865_bellman.java

저도 스키루트 문제는 플로이드로 해결했습니다.. 골목길은 제가 낸 문제지만 너무 어려워요..

1103 벨만포드 웜홀, 타임머신, Coolest Ski Route(플로이드) 

---

BOJ/1261.algospot/oh_1261_01BFS.java

 BOJ  1261.algospot

---

BOJ/2644. 촌수계산/oh_2644_floyd.java

 BOJ 2644. 촌수계산

---

SWEA/4192. 수영대회(완전탐색)/oh_4192.java

 SWEA 4192. 수영대회(완전탐색)

---

BOJ/2468. 안전영역/oh_2468.java

BOJ  2468. 안전영역

---

BOJ/20529. 가장 가까운 세사람의 심리적 거리/oh_20529.java

"나 좋아하지마"
"그게 뭔데"
"나 좋아하지 말라고"
"그거 어떻게 하는건데"

 BOJ  20529. 가장 가까운 세사람의 심리적 거리

---

SWEA/8382. 방향 전환/oh_8382.java

 SWEA 8382. 방향 전환 oh_8382

---

BOJ/14465. 소가 길을 건너간 이유 5/oh_14465.java

 BOJ  14465. 소가 길을 건너간 이유 5

---

BOJ/21921. 블로그/oh_21921.java

BOJ  21921. 블로그

---

BOJ/2671. 잠수함식별/haeun_2671.java
BOJ/9342. 염색체/haeun_9342.java
BOJ/9996. 한국이 그리울 땐 서버에 접속하지/haeun_9996.java
programmers/코딩테스트연습/2021 KAKAO BLIND RECRUITMENT/신규아이디추천/haeun.java

정규표현식 문제풀이

---

BOJ/9342. 염색체/oh_9342.java

 BOJ  9342. 염색체

---

BOJ/9996. 한국이 그리울 땐 서버에 접속하지/oh_9996.java

 BOJ 9996. 한국이 그리울 땐 서버에 접속하지

---

BOJ/1238. 파티/chan_1238.java
BOJ/1719. 택배/chan_1719.java
BOJ/5972. 택배배송/chan_5972.java

- BOJ 1719. 택배
- BOJ 1238. 파티
- BOJ 5972. 택배배송

다익스트라 주말 문제 풀이

---

BOJ/1238. 파티/ch_1238.java
BOJ/1719. 택배/ch_1719.java
BOJ/5972. 택배배송/ch_5972.java

다익스트라 문제풀이

---

BOJ/5972. 택배배송/oh_5972.java

 BOJ 5972. 택배배송

---

BOJ/1238. 파티/oh_1238.java

 BOJ  1238. 파티

---

programmers/2021 Dev-Matching/로또의 최고 순위와 최저 순위/chan.java

level 1 - 로또의 최고 순위와 최저 순위

---

programmers/2020 KAKAO BLIND RECRUITMENT/문자열 압축/oh_문자열압축.java

2020 KAKAO BLIND RECRUITMENT
문자열 압축

 2020 KAKAO BLIND RECRUITMENT  문자열 압축

---

programmers/2022 KAKAO BLIND RECRUITMENT/신고 결과 받기/oh_신고결과받기.java

programmers
2022 KAKAO BLIND RECRUITMENT
신고 결과 받기

 programmers / 2022 KAKAO BLIND RECRUITMENT

---

programmers/2017 카카오코드 예선/카카오프렌즈 컬러링북/mj.java
programmers/2021 KAKAO BLIND RECRUITMENT/신규아이디추천/mj.java

programmers L1

---

programmers/2020 카카오 인턴십/키패드 누르기/ch.java
programmers/Summer,Winter Coding(2019)/멀쩡한 사각형/ch.java

프로그래머스 lv1 lv2 문제 풀이

---

BOJ/14728. 벼락치기/oh_14728.java

 BOJ14728. 벼락치기

---

BOJ/18405.경쟁적 전염/oh_18405.java

 BOJ18405.경쟁적 전염

---

BOJ/2573. 빙산/oh_2573.java

 BOJ2573. 빙산

---

BOJ/18223.민준이와마산그리고건우/oh_18223.java

 BOJ18223.민준이와마산그리고건우

---

BOJ/1707. 이분 그래프/oh_1707.java

 BOJ 1707. 이분 그래프

---

BOJ/1245.농장관리/oh_1245.java

 BOJ 1245.농장관리

---

BOJ/16234. 인구이동/oh_16234.java

 BOJ 16234. 인구이동

---

BOJ/17142. 연구소3/oh_17142.java

 BOJ17142. 연구소3

---

BOJ/1446.지름길/oh_1446.java

 BOJ1446.지름길

---

BOJ/13424.비밀모임/oh_13424.java

 BOJ13424.비밀모임

---

BOJ/15683.감시/oh_15683.java

BOJ15683.감시

---

BOJ/14719.빗물/oh_14719.java

 BOJ14719.빗물

---

BOJ/15662.톱니바퀴2/oh_15662.java

 BOJ15662.톱니바퀴2

---

BOJ/21610. 마법사 상어와 비바라기/oh_21610.java

BOJ21610. 마법사 상어와 비바라기
